const errorCodes = {
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  INVALID_CODE:"INVALID_CODE"
};

module.exports = errorCodes;
