const errorCodes = {
  EMAIL_TAKEN: "EMAIL_TAKEN",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  ALREADY_VERIFIED: "ALREADY_VERIFIED",
  INVALID_CODE: "INVALID_CODE",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  EMAIL_NOT_VERIFIED: "EMAIL_NOT_VERIFIED",
};

module.exports = errorCodes;
